export const userContants = {
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",
  EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
  EDIT_USER_FAILURE: "EDIT_USER_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LLOGIN_FAILURE",
  LOGOUT_USER: "LOGOUT_USER",
  GETALL_USERS_SUCCESS: "GETALL_USERS_SUCCESS",
  GETALL_USERS_FAILURE: "GETALL_USERS_FAILURE ",
};
